on:
  push:
    branches:
      - main
    paths:
      - backend
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Setup yarn 
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 16

      - name: Build Backend
        run: |
          cd backend
          yarn install

      - name: Configure SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with: ${{ secrets.AWS_EC2_PRIVATE_KEY }}

      - name: Deploy Backend to AWS EC2
        uses: appleboy/scp-action@v0.1.4 
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          source: "backend/dist/app.js,backend/dist/controllers,backend/dist/middleware,backend/dist/routes"
          target: /var/www/html/api/
